# Generated by Django 2.2.1 on 2019-06-26 16:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matzip_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.TextField(blank=True)),
                ('category', models.TextField(blank=True)),
                ('review', models.IntegerField(blank=True)),
                ('tv', models.TextField(blank=True)),
                ('biztel', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('Menu', models.TextField(blank=True)),
                ('homepage', models.TextField(blank=True)),
                ('facebook', models.TextField(blank=True)),
                ('instagram', models.TextField(blank=True)),
                ('blog', models.TextField(blank=True)),
                ('web_site', models.TextField(blank=True)),
                ('convenience', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('age10', models.CharField(blank=True, max_length=50)),
                ('age20', models.CharField(blank=True, max_length=50)),
                ('age30', models.CharField(blank=True, max_length=50)),
                ('age40', models.CharField(blank=True, max_length=50)),
                ('age50', models.CharField(blank=True, max_length=50)),
                ('age60', models.CharField(blank=True, max_length=50)),
                ('Female', models.CharField(blank=True, max_length=50)),
                ('male', models.CharField(blank=True, max_length=50)),
                ('images_url_preprocess', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('matzip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Matzip_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='posts/images')),
                ('like_users', models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
