# Generated by Django 2.2.1 on 2019-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matzip_list',
            name='new_urls',
            field=models.URLField(blank=True),
        ),
    ]
